### PR TITLE
test fix for iTerm quiet opening config

### PR DESCRIPTION
**Pull request by luckman212**
see https://www.alfredforum.com/topic/18924-custom-terminal-script-causing-alfred-5-to-hang

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for submitting the fix! Question: which method are you using to start with no windows? Perhaps we can do something automatically (reading preferences) to auto-determine when that’s enabled and act accordingly (i.e. without the user having to change a specific setting in the script’s config).

**Comment by luckman212** [comment]
Thanks. I can't remember if or where in the GUI this is configured, but I looked at the prefs plist and it appears to be one or all of

```
$ defaults read com.googlecode.iterm2 | grep -i startup

    OpenArrangementAtStartup = 0;
    OpenNewWindowAtStartup = 0;
    OpenNoWindowsAtStartup = 1;

```

**Comment by luckman212** [comment]
I pushed another small change that adds a timeout so at least the script doesn't loop forever.

**Comment by luckman212** [comment]
image

**Comment by luckman212** [comment]
Not sure if parsing the prefs plist every time is worth the extra overhead of just documenting & setting the property. I seem to be one of the only people affected by this anyway, hate to slow down everyone else's workflows just to implement that. @vitorgalvao

**Comment by luckman212** [comment]
I experimented and found that these are the relevant pref keys:

to turn **ON** "quiet" open mode (no windows open when launched from Dock):
```shell
defaults write com.googlecode.iterm2 OpenNewWindowAtStartup -bool FALSE
defaults write com.googlecode.iterm2 OpenNoWindowsAtStartup -bool TRUE
```

to turn **OFF** quiet mode:
```shell
defaults write com.googlecode.iterm2 OpenNewWindowAtStartup -bool TRUE
defaults write com.googlecode.iterm2 OpenNoWindowsAtStartup -bool FALSE
```

**Comment by luckman212** [comment]
I saw your note about `"with timeout" does not work with a "repeat"` but I am not using `with timeout` I am using `repeat until...` which definitely works, I tested it.

**Comment by vitorgalvao** [comment]
> Not sure if parsing the prefs plist every time is worth the extra overhead of just documenting & setting the property.

Agreed. If there were a simple way to read the preferences from AppleScript (like the `defaults` command) it should be worth it as those are cached by macOS. But there seems to be no such way (`do shell script` and parsing the response isn’t great either).

> Nevermind, I see what you did there.

Yep, the comment is so someone arriving later knows that was tried. If it worked, it would have been the cleanest way.

Looks like this is good to go! I’ll merge and make a new release. Thank you again. Have a nice weekend!

**Pull request merged**
